auth-server:
  http://localhost:8181
realm-name:
  spring-boot
server:
  servlet:
    context-path: /profile
  port: 8003
spring:
  main:
    allow-circular-references: true # it is now forbidden by default to use circular dep-s. To be able to use self injection manually allow it using this flag
  application:
    name: profile-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/profiles
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth-server}/realms/${realm-name}
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: trace
        transaction: trace
        security: DEBUG